### PR TITLE
Update README.md with conda pycharm instructions

### PR DESCRIPTION
**Pull request by mducle**
**Description of work:**

Adds some instructions to the README to work with the new Mantid conda packages in PyCharm.

**To test:**

Check that the instructions work for you (I've only tested on Windows).

No associated issue

### CODE REVIEW

**Review by SilkeSchomann — CHANGES_REQUESTED** [review]
I've followed the instructions but had to make two small modifications to run or debug the tests:
In the `Nosetests` configuration I had to set the environment variable QT_QPA_PLATFORM_PLUGIN_PATH to the qt5 plugin of my environment (C:\Users\eoc57742\Miniconda3\envs\mantidnightly\Library\plugins\qt5).
In mslice/models/workspacemanager/workspace_algorithms.py I had to add import mslice.util.mantid.init_mantid. Should the second modification just get changed in general for MSlice?

**Comment by mducle** [comment]
> In the Nosetests configuration I had to set the environment variable QT_QPA_PLATFORM_PLUGIN_PATH to the qt5 plugin of my environment (C:\Users\eoc57742\Miniconda3\envs\mantidnightly\Library\plugins\qt5).

Ah right... it's weird I don't have to do that. I'm using mamba-forge but that shouldn't make a difference. Oh well, I'll put this change in.

> In mslice/models/workspacemanager/workspace_algorithms.py I had to add `import mslice.util.mantid.init_mantid`. Should the second modification just get changed in general for MSlice?

Oh yeah, I had to do that on Windows too (but strangely not on Linux... :shrug: 

I think it's safe enough to add it in general.

**Comment by SilkeSchomann** [comment]
Maybe we should add a comment to check for `import mslice.util.mantid.init_mantid` in mslice/models/workspacemanager/workspace_algorithms.py for users with an older version of MSlice.

**Comment by mducle** [comment]
So I think in normal usage this gets imported in either `mslice.app` or `mslice.cli` so users won't get this error unless they import `workspace_algorithms` directly (rather than through the documented `mslice.cli`). It's just that for some reason nosetest on Windows does a direct import whereas on Linux it doesn't... [sometimes coding feels like magic...]

**Review by SilkeSchomann — APPROVED** [review]
This works for me

**Pull request merged**
