### PR TITLE
Show when MSlice is busy

### LINKED ISSUE #81: Show when mslice is busy
When dealing with large datasets instruments scientist want a way to see if mslice is currently busy working on a large dataset or if it idle.
A suggestion was a red symbol in the status bar while mslice is busy.
 Although this issue is a seperate issue form #37 it would make sense to tackle them at the same time to avoid having to change features after implementing them

### PR DESCRIPTION
**Pull request by MatthewBowles**
Added a label to the bottom-right corner of the main window that displays 'Busy' if MSlice is working and 'Idle' if it is waiting for input.

**To test:**
- Open MSlice and run any load / calculate projections / slice / cut operation
- Verify 'Busy' appears appropriately.

Fixes #81

### CODE REVIEW

**Comment by martyngigg** [comment]
@MatthewBowles There's a failure on the travis CI build.

**Comment by MatthewBowles** [comment]
@martyngigg Not sure why this build is failing. Any ideas?

**Comment by martyngigg** [comment]
@MatthewBowles  The last line of the log says `QWidget: Must construct a QApplication before a QPaintDevice`. This happens when any class deriving from `QWidget` has been constructed before a `QApplication` object.

Do the tests run on your machine?

**Comment by MatthewBowles** [comment]
@martyngigg Yes, all the tests pass.
It might be the self.busy_text QLabel in MainWindow's init, but I thought that was supposed to run after the QApplication constructor, and I'm not sure where to move it to.

**Comment by MatthewBowles** [comment]
@martyngigg Thanks for the help, it seems to be working now.

**Pull request merged**
