### PR TITLE
Informational overplot - recoil lines

### PR DESCRIPTION
**Pull request by MatthewBowles**
Plot recoil lines over slices (from issue #163).

Added options to the Information -> Recoil lines menu on slices to toggle Hydrogen, Deuterium or Helium recoil lines. There is also an option to plot any other atom by entering the relative mass.

### CODE REVIEW

**Comment by martyngigg** [comment]
@MatthewBowles We've got a few conflicts here now.

**Comment by martyngigg** [comment]
@MatthewBowles I think this is a good start. I think, though, that we will need someway of marking what the lines mean. If I had all 3 hydrogen isotope lines I just have 3 green lines and it's hard to remember what is what. I think they should certainly be different colours and maybe then we could add a legend?

Or the other option would be try to annotate the line with some text. @mducle Any ideas for how you would like to see this?

**Comment by mducle** [comment]
@martyngigg @MatthewBowles I think that it's ok as it is - the lines with heavier isotopes will extend further out in |Q| for a given energy transfer. However, if it's not a lot of effort, then you make them different colors and if a user plots two (or more) lines then to bring up the legends key box showing which is which.

However, I have spotted a problem with the calculation of the lines themselves - in line 113 of `mslice/models/slice/mantid_slice_algorithm.py` instead of

```
line = np.square(momentum_transfer * HBAR_MEV) / (2 * relative_mass * constants.neutron_mass)
```

it should be:

```
line = np.square(momentum_transfer * 1.e10 * constants.hbar) / (2 * relative_mass * constants.neutron_mass) / (constants.elementary_charge / 1000)
```

This is because `constants.neutron_mass` is in SI units (in kilograms) so we can't mix the units by using `hbar` in `meV` and momentum transfer in Angstrom^-1 -- we have to convert everything into SI and then convert back to `meV` (with the term in the last bracket).

**Comment by martyngigg** [comment]
Thanks, @mducle. I hadn't gotten to checking the formulae yet.

@MatthewBowles Would the different line colours and legend be much work?

**Comment by MatthewBowles** [comment]
@martyngigg Not at all, I can do that.

**Pull request merged**
