### PR TITLE
Added section on how to save multiple files via CLI

### LINKED ISSUE #1023: Saving multiple cuts via command-line interface
When a user needs to save several cuts as ASCII files, it is often easier to use the command-line interface with save_ascii instead of the GUI. It would be good to have a section in the MSlice documentation describing this, preferably with an example script.

### PR DESCRIPTION
**Pull request by SilkeSchomann**
**Description of work:**
Added an example script for saving multiple cuts as ASCII files. 

Also, corrected an import error in the section "Plotting a series of cuts".

**To test:**

Read instructions and see whether they make sense. Try out the example script.

Fixes #1023.

### CODE REVIEW

**Review by GuiMacielPereira — CHANGES_REQUESTED** [review]
I just wanted to check that when I run the script, it successfully creates and saves the cuts, but if I try to plot the cuts in mantid, the legend is not visible and I get the following warning:
```
The label '__MSLMAR25087_Ei40.00meV_cut(1.500,2.500)' of <matplotlib.lines.Line2D object at 0x7d490aaed360> starts with '_'. It is thus excluded from the legend.
```

This is fine, right?

**Comment by SilkeSchomann** [comment]
This is weird, I cannot reproduce it. Which steps are you following when plotting the cuts?

**Comment by GuiMacielPereira** [comment]
I was just running the script inside Mantid and then double clicking on the workspaces to plot

**Comment by SilkeSchomann** [comment]
The workspace in MSlice or in Mantid?

**Comment by GuiMacielPereira** [comment]
In Mantid :thinking:

**Comment by SilkeSchomann** [comment]
In that case, it is not a problem. It means you are displaying hidden workspaces in Mantid and the warning is useful in case a user does the same. These workspaces are all accessible through the MDHisto tab in MSlice after running the script. There they are not hidden, and the warning does not show up when the user clicks the `Plot` button.

**Review by GuiMacielPereira — APPROVED** [review]
I just confirmed that the workspaces correctly appear on mslice :+1:

**Pull request merged**
