### PR TITLE
Add SaveAscii to _mslice_commands

### LINKED ISSUE #468: Add file I/O commands to mslice.cli namespace
A user has requested the ability to save text files of workspaces from the CLI. At the moment this is possible but convoluted, e.g. 

```python
import mslice.cli as mc
import mslice.models.workspacemanager.file_io as mio

ws = mc.Load('file')
cut_ws = mc.Cut(ws, CutAxis="DeltaE,5.0,55.0,0.3", IntegrationAxis="|Q|,0.0,9.0,0.0", NormToOne=False)
slice_ws = mc.Slice(ws, Axis1="|Q|,0.27356,11.0351,0.04671", Axis2="DeltaE,-241.97,469.41,2.42,cm-1", NormToOne=False)

mio.save_ascii(cut_ws, '/tmp/cut.txt', is_slice=False)
mio.save_ascii(slice_ws, '/tmp/slice.txt', is_slice=True)
```

It would be good to have a wrapper in `mslice.cli` to do this (especially checking `is_slice`), and maybe to look up the workspace handle if the user gives a workspace name (string).

### PR DESCRIPTION
**Pull request by aybamidele**
I added a `SaveAscii` function to the CLI as requested in #468. The Ascii files can be saved either by using the workspace name or workspace handle.
**To test:**
Open MSlice
Run the following code:
```python
import mslice.cli as mc
ws = mc.Load('/home/andre/Downloads/mslice_test_data/MAR21335_Ei60.00meV.nxs')

cut_ws = mc.Cut(ws, CutAxis="DeltaE,5.0,55.0,0.3", IntegrationAxis="|Q|,0.0,9.0,0.0", NormToOne=False) #MSlice saves the workspace as 'MAR21335_Ei60.00meV_cut(0.000,9.000)'

slice_ws = mc.Slice(ws, Axis1="|Q|,0.27356,11.0351,0.04671", Axis2="DeltaE,-241.97,469.41,2.42,cm-1", NormToOne=False) #MSlice saves the workspace as '__MAR21335_Ei60.00meV'

mc.SaveAscii(cut_ws, '/home/andre/Downloads/ascii') #or
mc.SaveAscii('MAR21335_Ei60.00meV_cut(0.000,9.000)', '/home/andre/Downloads/ascii')

mc.SaveAscii(slice_ws, '/home/andre/Downloads/ascii2') #or
mc.SaveAscii('__MAR21335_Ei60.00meV', '/home/andre/Downloads/ascii2')
```

Fixes #468.

### CODE REVIEW

**Comment by aybamidele** [comment]
The failing tests are due to `ImportError: No module named mantidqt.icons`

**Comment by martyngigg** [comment]
My apologies for not seeing this last week. I've fixed the build script but there seems to be a failing CLI test.

**Comment by aybamidele** [comment]
@mducle Concerning the failing test, I wanted to ask what category histogram workspaces should fall under. Are they under slices or cuts?

**Comment by mducle** [comment]
@aybamidele Sorry for the late reply - I think in this case the histogram workspace should be a slice (because it has 2 dimension) - the main distinction between cuts and slice is that cuts are 1D, slices are 2D. The following changes to `is_cut` and `is_slice` makes the test work for me:

```diff
diff --git a/mslice/cli/helperfunctions.py b/mslice/cli/helperfunctions.py
index 8d2f979..cc51455 100644
--- a/mslice/cli/helperfunctions.py
+++ b/mslice/cli/helperfunctions.py
@@ -144,7 +144,7 @@ def is_slice(*args):
     """
     if not isinstance(args[0], Workspace) or is_cut(*args):
         return False
-    if isinstance(args[0], Workspace) or args[0].getNumDims() == 2:
+    if isinstance(args[0], Workspace) or args[0]._raw_ws.getNumDims() == 2:
         return True
 
 
@@ -152,7 +152,7 @@ def is_cut(*args):
     """
     Checks if args[0] is a HistogramWorkspace
     """
-    if isinstance(args[0], HistogramWorkspace):
+    if isinstance(args[0], HistogramWorkspace) and args[0]._raw_ws.getNumDims() == 1:
         return True
     else:
         return False
```

**Comment by martyngigg** [comment]
We could just accept the complexity increase in the presenter with a `noqa` as it's just a flat list of `if` and fairly easy to read. If it gets much longer though we'd probably want to refactor some kind of dictionary mapping to handlers.

**Comment by mducle** [comment]
Weird thing is that it only shows up on some servers: `ornl-ubuntu-builder` and `ornl-pc84929` so far. `ornl-ubuntu-builder2` and `isis-ndw1441` both seem ok with that `flake8` check.

I've made an issue for it: #478 and I was going to change the `if` / `elif` blocks to a map for the `notify` routine and hive off some parts of `get_algorithm_kwargs` into a helper function.

**Comment by martyngigg** [comment]
I'm getting an error on saving the slice workspace:
```python
Traceback (most recent call last):
  File "saveasciitest.py", line 11, in <module>
    mc.SaveAscii(slice_ws, 'ascii2.txt') #or
  File "/media/data1/source/github/mantidproject/mslice/mslice/cli/_mslice_commands.py", line 102, in SaveAscii
    save_ascii(InputWorkspace, Path, is_slice(InputWorkspace))
  File "/media/data1/source/github/mantidproject/mslice/mslice/models/workspacemanager/file_io.py", line 60, in save_ascii
    _save_slice_to_ascii(workspace, path)
  File "/media/data1/source/github/mantidproject/mslice/mslice/models/workspacemanager/file_io.py", line 118, in _save_slice_to_ascii
    ix = [i for i, ax in enumerate(workspace.axes) if 'DeltaE' in ax.units][0]
IndexError: list index out of range
```

**Comment by mducle** [comment]
@martyngigg Sorry it was a bug introduced in PR 471: https://github.com/mantidproject/mslice/pull/471/files#diff-e5a81a1ac22bb7b1e7b419dd58b81638R55 - it should be fixed now. I've also changed the code a bit to save `.mat` and `.nxs` files too.

**Pull request merged**
