### PR TITLE
CLI - Plot Cut Command

### LINKED ISSUE #325: Add plot commands to CLI
Add conversion commands for plotting via matplotlib e.g.
```
plt.imshow(slice_data(slice)))
```
or
```
x, y, e = cut_xye(cut)
plt.errorbar(x, y, e, ...)

### PR DESCRIPTION
**Pull request by MatthewBowles**
Adds `PlotCut` command to CLI that creates the standard figure as if plotted from the GUI.

**To test:**
e.g.
```
ws = Load('MAR21335_Ei60.00meV.nxs')
cut = Cut(ws, CutAxis='|Q|,0,12,.05', IntegrationAxis='DeltaE,-1,1,0')
PlotCut(cut, IntensityEnd=200, PlotOver=True)
```

Fixes #325

### CODE REVIEW

**Comment by martyngigg** [comment]
It also looks like there are some conflicts here now from merging the slice command PR.

**Comment by MatthewBowles** [comment]
I agree we need unit tests, I was planning to add these before merging `cli` into `master`, but I think it's more important that I get the history working first.

**Comment by martyngigg** [comment]
Cuts and slices seem to work as expected now. There's still a build failure though.

**Comment by MatthewBowles** [comment]
@martyngigg I've added some tests, should be ok to merge now.

**Comment by martyngigg** [comment]
Thanks for the tests - I think they will be valuable.

The cutting seems to work fine still but I can't get the slicing to work:
```
In [1]: ws = Load('/home/dmn58364/mslice/MAR21335_Ei60.00meV.nxs')

In [2]: cut = Cut(ws, CutAxis='|Q|,0,12,.05', IntegrationAxis='DeltaE,-1,1,0')

In [3]: PlotCut(cut)
/usr/lib/python2.7/dist-packages/numpy/ma/core.py:4139: UserWarning: Warning: converting a masked element to nan.
  warnings.warn("Warning: converting a masked element to nan.")

In [4]: sl = Slice(ws)

In [5]: PlotSlice(sl)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-a85420539f7d> in <module>()
----> 1 PlotSlice(sl)

/media/data1/source/github/mantidproject/mslice/mslice/cli/_mslice_commands.pyc in PlotSlice(InputWorkspace, IntensityStart, IntensityEnd, Colormap)
    184     workspace = get_workspace_handle(InputWorkspace)
    185     if not isinstance(workspace, HistogramWorkspace):
--> 186         raise RuntimeError("Incorrect workspace type.")
    187     slice_presenter = app.MAIN_WINDOW.slice_plotter_presenter
    188     slice_presenter.change_intensity(workspace.name, IntensityStart, IntensityEnd)

RuntimeError: Incorrect workspace type.
```
Am I doing something wrong? Can the new tests pick this up?

**Comment by MatthewBowles** [comment]
Looks like I missed a test case, should be fixed now.

**Pull request merged**
