### PR TITLE
Do not clear error messages after a timeout

### LINKED ISSUE #75: Make errors persist until a button is clicked
Currently all errors in mslice will stay on the screen for 2 seconds. Errors should remain on screen until a button is clicked

### PR DESCRIPTION
**Pull request by EltayebAhmed**
Errors will stay in the statusbar until a button is clicked

**To test:**

1. Launch the mslice GUI.
2. Click on remove workspace without any workspace selected. An error will appear
3. Clicking on any other button will cause the error to disappear. 

Fixes #75

### CODE REVIEW

**Comment by martyngigg** [comment]
@EltayebAhmed Please improve the title of the PR so that it doesn't contain an issue number and reads as a short summary

**Comment by martyngigg** [comment]
@EltayebAhmed This is related to errors and I found this while testing this PR.

If you start `mslice` and just click "calculate projection" you get the following error in the console but nothing displayed in the GUI:

```Traceback (most recent call last):
  File "/mnt/data1/source/github/mantidproject/mslice/widgets/projection/powder/powder.py", line 34, in _btn_clicked
    self._presenter.notify(Command.CalculatePowderProjection)
  File "/mnt/data1/source/github/mantidproject/mslice/presenters/powder_projection_presenter.py", line 31, in notify
    self._calculate_powder_projection()
  File "/mnt/data1/source/github/mantidproject/mslice/presenters/powder_projection_presenter.py", line 46, in _calculate_powder_projection
    raise NotImplementedError('Implement error message')
NotImplementedError: Implement error message
```

Do you have time it would be good to look at this?

**Comment by EltayebAhmed** [comment]
There is already an issue for this #38

**Comment by martyngigg** [comment]
@EltayebAhmed Ok, thanks. We can leave this to be addressed separately.

**Pull request merged**
