### PR TITLE
Fix UI building script

### PR DESCRIPTION
**Pull request by EltayebAhmed**
**To Test:**
Run the build all_all_ui_files.py script
All <foo>.ui files will be built to <foo>_ui.py

### CODE REVIEW

**Comment by OwenArnold** [comment]
@EltayebAhmed Can you link your PRs to your Issues please 
**Example**
Fixes #6

**Comment by EltayebAhmed** [comment]
@OwenArnold I have added the docstrings

**Comment by martyngigg** [comment]
I think we have an ordering problem here and you won't see it as the files are already on your machine.

In `mslice.py` there is an import `from mslice_ui import Ui_MainWindow` but I assume this is meant to be generated from `mslice.ui`?

I'm not sure what the best practice is here. Should we be compiling all files on first import or should we assume the compile as been done by an external tool. That way we know exactly what files are there. I'm thinking that when we come to deployment the various installers generally tend to like to know the exact files that they will need to install to be able to uninstall successfully.

@EltayebAhmed I would be inclined to say keep this script for yourself for now and then make an issue for implementing a cmake configuration for this so that it can be incorporated into the Mantid build process more easily.

@OwenArnold What do you think?

**Comment by OwenArnold** [comment]
@martyngigg Yes, good point with the installers. I agree.

**Comment by martyngigg** [comment]
I've had a rethink and it probably makes more sense for this to be defined as a `distuils` project - https://docs.python.org/2/distutils/. We can still import this into the Mantid build if it set up like that but it leaves scope for redefining other projects as more standard python packages.

**Comment by martyngigg** [comment]
http://hg.logilab.org/review/hgview/file/tip/setup.py seems to offer hints at a good way of doing this for PyQt-based applications.

**Comment by martyngigg** [comment]
@EltayebAhmed I can now build all of the `.ui` files but I get the following error when starting mslice with `python mslice.py`
```python
FrameworkManager-[Notice] Welcome to Mantid 3.7.1
FrameworkManager-[Notice] Please cite: http://dx.doi.org/10.1016/j.nima.2014.07.029 and this release: http://dx.doi.org/10.5286/Software/Mantid3.7.1
Warning :: Using MSlice Figures because get_figure_class is still not implemented
Traceback (most recent call last):
  File "mslice.py", line 4, in <module>
    from mslice_ui import Ui_MainWindow
  File "/mnt/data1/source/github/mantidproject/mslice/mslice_ui.py", line 118, in <module>
    from widgets.slice.slice import SliceWidget
  File "/mnt/data1/source/github/mantidproject/mslice/widgets/slice/slice.py", line 4, in <module>
    from models.slice.matplotlib_slice_plotter import MatplotlibSlicePlotter
  File "/mnt/data1/source/github/mantidproject/mslice/models/slice/matplotlib_slice_plotter.py", line 3, in <module>
    from plotting import pyplot as plt
  File "/mnt/data1/source/github/mantidproject/mslice/plotting/pyplot.py", line 1, in <module>
    from figuremanager import FigureManager,activate_category
  File "/mnt/data1/source/github/mantidproject/mslice/plotting/figuremanager.py", line 4, in <module>
    PlotFigure = get_figure_class()
  File "/mnt/data1/source/github/mantidproject/mslice/plotting/__init__.py", line 7, in get_figure_class
    from plotting.plot_window.plot_figure import PlotFigure
  File "/mnt/data1/source/github/mantidproject/mslice/plotting/plot_window/plot_figure.py", line 1, in <module>
    from plotting.plot_window_ui import Ui_MainWindow
ImportError: No module named plot_window_ui
```

**Comment by EltayebAhmed** [comment]
@martyngigg 
This is resolved in #10 and will most likely works in master. How Can i verify. This an old branch, Should I merge master into it?

**Comment by martyngigg** [comment]
@EltayebAhmed You're right, you just need to merge `master` to this branch and push it again.

**Comment by EltayebAhmed** [comment]
@martyngigg  merged master in

**Comment by EltayebAhmed** [comment]
Moving cursor out of bounds while zooming breaks zooming

**Comment by martyngigg** [comment]
I still see the same error regarding `plot_window_ui.py` being missing

**Comment by EltayebAhmed** [comment]
@martyngigg it works my machine

**Comment by EltayebAhmed** [comment]
@martyngigg Issue resolved

**Comment by martyngigg** [comment]
@EltayebAhmed Good. Once I built all of the `.ui` files then I was able to start the GUI successfully.

**Pull request merged**
